backend:
  name: github
  repo: haenny91/thetravelcuration
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        default: false
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Categories'
        name: 'categories'
        widget: 'list'  # <- 버튼형 리스트 위젯 활성화
      - label: 'Tags'
        name: 'tags'
        widget: 'list'  # <- 버튼형 리스트 위젯 활성화
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        default: false
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'